### ISSUE TITLE
It looks good, but there are a lot of bugs. So, come on

### ISSUE THREAD

**Issue by yaoqiangpersonal** [sancarn/VBA-STD-Library#3]
When the upper limit of stdarray is 0, pop error.
 Stdarray.every, CB (Parr (I)) parameter will be wrong, which makes it unusable.

**Comment by sancarn** [comment]
Yep, not surprising. Suggest using stdArrayReplica instead of stdArray as this is more optimum, although all of this is currently experimental.

Happy to take PRs or if you figure out a fix, happy to implement :)

Other changes will occur later as realistically cb should be ICallable to allow future lambda syntax.

**Comment by yaoqiangpersonal** [comment]
Wow, I got a reply. I tested stdarrayreplica.isevery, and I was very confused about this code {if not IIF (metadata is nothing, CB (Parr (I)), CB (metadata, Parr (I))) then}. In this way, CB will be called twice. I like using lambda very much, so I hope this project can continue.

**Comment by yaoqiangpersonal** [comment]
> Yep, not surprising. Suggest using stdArrayReplica instead of stdArray as this is more optimum, although all of this is currently experimental.
> 
> Happy to take PRs or if you figure out a fix, happy to implement :)
> 
> Other changes will occur later as realistically cb should be ICallable to allow future lambda syntax.
> 
> stdArray.pop() error on empty array does make sense. Not sure if this should be undefined or not...

Wow, I got a reply. I tested stdarrayreplica.isevery, and I was very confused about this code {if not IIF (metadata is nothing, CB (Parr (I)), CB (metadata, Parr (I))) then}. In this way, CB will be called twice. I like using lambda very much, so I hope this project can continue.

**Comment by sancarn** [comment]
IsEvery checks all entries against the callback, if any returns false, the function returns false. 

So if any returns false, iif will return false, if not false —> if true —> run code, exit function with false return value.

**Comment by sancarn** [comment]
I believe this is fixed now as `stdArrayReplica` has been moved into public `stdArray` library for increased stability. Let me know if I'm mistaken.
